# Data Quality Report

## Dataset Overview

- Total records: 1,845
- Total columns: 19
- Duplicate records: 25
- Missing values: Present
- Categorical inconsistencies: Present
- Numeric inconsistencies: Present
- Date inconsistencies: Present

### Categorical Issues
- `Branch` contains inconsistent capitalization and extra spaces.
- `Internship` contains multiple representations of Yes/No.
- `Placement_Status` contains inconsistent capitalization.
- `Gender` contains inconsistent capitalization.

### Numeric Issues
- `CGPA` contains invalid values outside the 0–10 range.
- `Attendance` contains values above 100%.
- `10th_Percentage` contains values greater than 100%.
- `12th_Percentage` contains values greater than 100%.

### Date Issues
- `Application_Date` contains multiple date formats.

In [43]:
import pandas as pd

df = pd.read_csv("student_placement_messy.csv")

In [24]:
# Dataset dimensions (No. of rows, No. of column)
df.shape

(1845, 19)

In [29]:
# First 5 Records
df.head()

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
0,ST0205,Student_0205,Female,Civil,8.39,73.89,91.41,81.18,1,No,3.0,6,8.0,8.0,70.32,Placed,12.33,2024,2023-06-01
1,ST0514,Student_0514,Female,CSE,6.85,81.80,83.22,89.46,0,Yes,0.0,5,4.0,10.0,65.44,Placed,8.07,2023,2024-01-17
2,ST0571,Student_0571,Female,ECE,7.89,65.41,70.56,56.04,1,No,5.0,1,2.0,1.0,51.71,Not Placed,NaN,2024,2024-02-28
3,ST0896,Student_0896,Female,CSE,7.11,77.41,50.46,79.67,1,No,4.0,3,7.0,10.0,71.42,Not Placed,0.0,2026,2024-10-27
4,ST1125,Student_1125,Female,IT,7.87,62.83,73.25,87.8,0,No,5.0,0,8.0,9.0,77.80,Not Placed,0.0,2023,2025-04-15

In [30]:
# Last 5 Records
df.tail()

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
1840,ST0078,Student_0078,Female,CSE,7.86,68.70,69.03,73.63,0,Yes,4.0,6,8.0,2.0,58.84,Not Placed,0.0,2023,2023-02-27
1841,ST0953,Student_0953,Male,Civil,5.53,66.48,80.87,99.13,0,Yes,1.0,0,10.0,6.0,55.79,Placed,10.84,2023,2024-12-09
1842,ST0795,Student_0795,Male,IT,7.59,74.19,85.32,80.66,0,No,1.0,4,4.0,4.0,77.74,Placed,11.54,2023,2024-08-13
1843,ST1415,Student_1415,Female,CIVIL,8.88,71.71,76.41,70.12,0,Yes,3.0,6,3.0,7.0,51.40,Placed,12.01,2025,2025-11-17
1844,ST0258,Student_0258,Female,Civil,6.58,67.84,73.45,73.62,1,No,2.0,1,2.0,3.0,67.15,Placed,10.79,2023,2023-07-11

In [32]:
# Column names
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Branch', 'CGPA', '10th_Percentage',
       '12th_Percentage', 'Attendance', 'Backlogs', 'Internship', 'Projects',
       'Certifications', 'Programming_Skill', 'Communication_Skill',
       'Aptitude_Score', 'Placement_Status', 'Package_LPA', 'Graduation_Year',
       'Application_Date'],
      dtype='str')

In [34]:
# Data types
df.dtypes

Student_ID                 str
Name                       str
Gender                     str
Branch                     str
CGPA                   float64
10th_Percentage        float64
12th_Percentage        float64
Attendance                 str
Backlogs                 int64
Internship                 str
Projects               float64
Certifications           int64
Programming_Skill      float64
Communication_Skill    float64
Aptitude_Score         float64
Placement_Status           str
Package_LPA                str
Graduation_Year          int64
Application_Date           str
dtype: object

In [36]:
# Complete structural information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1845 entries, 0 to 1844
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           1845 non-null   str
 1   Name                 1845 non-null   str
 2   Gender               1807 non-null   str
 3   Branch               1818 non-null   str
 4   CGPA                 1807 non-null   float64
 5   10th_Percentage      1845 non-null   float64
 6   12th_Percentage      1845 non-null   float64
 7   Attendance           1790 non-null   str
 8   Backlogs             1845 non-null   int64
 9   Internship           1817 non-null   str
 10  Projects             1819 non-null   float64
 11  Certifications       1845 non-null   int64
 12  Programming_Skill    1814 non-null   float64
 13  Communication_Skill  1815 non-null   float64
 14  Aptitude_Score       1799 non-null   float64
 15  Placement_Status     1829 non-null   str
 16  Package_LPA          1812 non-null   str
 17  Graduation_Year      1845 non-null   int64
 18  Application_Date     1830 non-null   str
dtypes: float64(7), int64(3), str(9)
memory usage: 375.2 KB

In [39]:
# Statistical overview
df.describe()

,CGPA,10th_Percentage,12th_Percentage,Backlogs,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Graduation_Year
count,1807.000000,1845.000000,1845.000000,1845.000000,1819.000000,1845.000000,1814.000000,1815.000000,1799.000000,1845.000000
mean,7.501350,74.742862,72.597252,0.744715,2.681143,2.965312,5.403528,5.527824,65.497665,2024.498645
std,1.049165,10.235479,11.943272,1.131477,1.473466,1.991547,2.837249,2.851946,14.777545,1.102956
min,0.000000,5.000000,10.000000,0.000000,-2.000000,0.000000,0.000000,0.000000,20.000000,2023.000000
25%,6.790000,68.350000,64.620000,0.000000,2.000000,1.000000,3.000000,3.000000,55.490000,2024.000000
50%,7.500000,74.870000,72.560000,0.000000,3.000000,3.000000,5.000000,5.000000,65.730000,2024.000000
75%,8.170000,81.520000,80.560000,1.000000,4.000000,5.000000,8.000000,8.000000,75.790000,2025.000000
max,12.000000,150.000000,130.000000,4.000000,15.000000,6.000000,15.000000,20.000000,100.000000,2026.000000

In [40]:
# Missing values
df.isnull().sum()

Student_ID              0
Name                    0
Gender                 38
Branch                 27
CGPA                   38
10th_Percentage         0
12th_Percentage         0
Attendance             55
Backlogs                0
Internship             28
Projects               26
Certifications          0
Programming_Skill      31
Communication_Skill    30
Aptitude_Score         46
Placement_Status       16
Package_LPA            33
Graduation_Year         0
Application_Date       15
dtype: int64

In [41]:
# Duplicate records
df.duplicated().sum()

np.int64(25)

In [42]:
# Unique values
df.nunique()

Student_ID             1800
Name                   1800
Gender                    4
Branch                   20
CGPA                    426
10th_Percentage        1407
12th_Percentage        1423
Attendance             1376
Backlogs                  5
Internship                7
Projects                  9
Certifications            7
Programming_Skill        13
Communication_Skill      13
Aptitude_Score         1475
Placement_Status          8
Package_LPA             624
Graduation_Year           4
Application_Date       1353
dtype: int64

# Categorical Inconsistencies Check

In [45]:
df['Internship'].unique()

<ArrowStringArray>
['No', 'Yes', ' yes ', 'NO', 'yes', 'No ', nan, 'YES']
Length: 8, dtype: str

In [46]:
df['Placement_Status'].unique()

<ArrowStringArray>
[    'Placed', 'Not Placed', 'Not placed',          nan, 'NOT PLACED',
 'not placed',   ' placed ',     'PLACED',     'placed']
Length: 9, dtype: str

In [47]:
df['Branch'].unique()

<ArrowStringArray>
[      'Civil',         'CSE',         'ECE',          'IT',         'cse',
  'Mechanical',     ' Civil ',          'it',        'ECE ',         'IT ',
           nan,  'mechanical',       'civil',        ' ECE',         ' IT',
         'ece',        ' CSE', 'Mechanical ',        'CSE ',       'CIVIL',
 ' MECHANICAL']
Length: 21, dtype: str

In [48]:
df['Gender'].unique()

<ArrowStringArray>
['Female', 'Male', 'male', nan, 'female']
Length: 5, dtype: str

# Numeric Inconsistencies Check

In [51]:
df['CGPA'].describe()

count    1807.000000
mean        7.501350
std         1.049165
min         0.000000
25%         6.790000
50%         7.500000
75%         8.170000
max        12.000000
Name: CGPA, dtype: float64

In [52]:
df[df['CGPA']>10]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
80,ST0212,Student_0212,Male,CSE,11.0,91.38,81.49,78.59,0,No,3.0,6,5.0,1.0,83.96,Not Placed,0.0,2026,2023-06-06
155,ST0672,Student_0672,Female,CSE,12.0,84.37,64.05,NaN,0,Yes,2.0,0,3.0,5.0,54.04,Not Placed,0.0,2023,2024-05-14
611,ST0218,Student_0218,Male,Civil,12.0,74.05,85.83,82.93,0,No,4.0,0,5.0,4.0,64.64,Placed,7.97,2026,2023-06-11
827,ST0045,Student_0045,Female,CSE,12.0,78.56,76.39,72.65,0,Yes,4.0,6,8.0,10.0,59.78,Not Placed,₹0.0,2026,2023-02-02
1302,ST0281,Student_0281,Female,Civil,12.0,72.44,72.35,85.77,4,No,2.0,6,3.0,5.0,59.77,Placed,12.78,2024,2023-07-28
1426,ST0013,Student_0013,Male,ECE,11.0,69.03,73.22,87.95,0,No,2.0,1,2.0,5.0,81.02,Placed,9.34,2025,2023-01-09
1544,ST0218,Student_0218,Male,Civil,12.0,74.05,85.83,83.93,0,No,4.0,0,5.0,4.0,64.64,Placed,7.97,2026,2023-06-11

In [55]:
df['Attendance'].describe()

count      1790
unique     1376
top       100.0
freq         44
Name: Attendance, dtype: object

In [71]:
df['Attendance'].max()

'99.92'

In [73]:
df['Attendance'].map(type).value_counts(dropna=False)

Attendance
<class 'str'>      1790
<class 'float'>      55
Name: count, dtype: int64

In [57]:
df['10th_Percentage'].describe()

count    1845.000000
mean       74.742862
std        10.235479
min         5.000000
25%        68.350000
50%        74.870000
75%        81.520000
max       150.000000
Name: 10th_Percentage, dtype: float64

In [58]:
df[df['10th_Percentage']>100]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
103,ST1789,Student_1789,Male,IT,8.45,105.0,46.83,75.36,0,No,4.0,2,7.0,9.0,76.91,Placed,12.88,2025,2026-08-22
672,ST1635,Student_1635,Male,Mechanical,7.73,105.0,84.42,89.39,0,No,3.0,4,8.0,1.0,67.63,Placed,11.97,2023,2026-04-30
1272,ST1677,Student_1677,Male,Civil,7.53,105.0,68.87,90.53,0,No,2.0,1,2.0,5.0,77.22,Not Placed,0.0,2024,31/05/2026
1471,ST0895,Student_0895,Female,CSE,5.63,150.0,65.80,86.13,0,No,2.0,3,2.0,5.0,86.03,Placed,8.51,2025,2024-10-26
1738,ST0734,Student_0734,Female,Mechanical,8.18,105.0,79.59,79.14,0,Yes,2.0,3,2.0,2.0,66.25,Placed,12.41,2024,2024-06-29

In [59]:
df['12th_Percentage'].describe()

count    1845.000000
mean       72.597252
std        11.943272
min        10.000000
25%        64.620000
50%        72.560000
75%        80.560000
max       130.000000
Name: 12th_Percentage, dtype: float64

In [60]:
df[df['12th_Percentage']>100]

,Student_ID,Name,Gender,Branch,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Internship,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Placement_Status,Package_LPA,Graduation_Year,Application_Date
27,ST0785,Student_0785,Female,CSE,8.19,75.81,130.0,88.64,1,yes,5.0,2,3.0,7.0,57.20,Placed,₹9.82,2023,08-06-2024
385,ST0931,Student_0931,Male,Civil,7.82,70.24,130.0,72.5,0,No,0.0,0,8.0,5.0,67.83,Placed,9.12,2026,2024-11-22
896,ST0184,Student_0184,male,Civil,8.00,59.70,130.0,83.33,3,Yes,1.0,6,8.0,5.0,56.66,Placed,11.83,2024,2023-05-17

In [61]:
df['Aptitude_Score'].describe()

count    1799.000000
mean       65.497665
std        14.777545
min        20.000000
25%        55.490000
50%        65.730000
75%        75.790000
max       100.000000
Name: Aptitude_Score, dtype: float64

# Date Inconsistencies Check

In [63]:
df["Application_Date"].unique()

<ArrowStringArray>
['2023-06-01', '2024-01-17', '2024-02-28', '2024-10-27', '2025-04-15',
 '2025-03-25', '2023-09-16', '2025-06-17', '2024-10-09', '2023-09-07',
 ...
 '2024-11-12', '2024-04-08', '2024-07-30', '2025-02-20', '2024-06-17',
 '2024-04-22', '2023-09-05', '2023-02-27', '2024-08-13', '2025-11-17']
Length: 1354, dtype: str

In [67]:
df["Application_Date"].sample(30, random_state=42)

1572    2025-01-30
1160    2024-05-18
799            NaN
1531    2024-10-22
1323    2025-07-06
361     08-24-2025
239     2023-05-02
582     2026-02-10
1440    2024-06-05
1283    2026-01-14
1613    2025-09-08
607     2023-07-09
1284    2025-02-21
1087    2026-06-22
584     2024-06-06
1822    2024-11-12
1488    2025-10-15
1301    2024-04-16
1791    2025-07-11
1835    2025-12-21
1036    2025-06-20
700     2024-02-22
1561    2025-11-20
382     2025-12-06
1833    2023-01-21
1242    2024-08-01
351     2025-11-28
303     2025-12-25
764     2026-06-02
1360    2025-07-29
Name: Application_Date, dtype: str