### Placement Overview

The dataset contains 1820 students with known placement status.

- Placed: 1311 students (72.03 %)
- Not placed: 493 students (27.08 %)

This provides the baseline placement outcome for further analysis.

In [6]:
import pandas as pd

df = pd.read_csv('Student_clean_data.csv')

## Dataset Overview

In [7]:
df.shape

(1820, 19)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1820 entries, 0 to 1819
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           1820 non-null   str
 1   Name                 1820 non-null   str
 2   Gender               1820 non-null   str
 3   Branch               1820 non-null   str
 4   CGPA                 1775 non-null   float64
 5   10th_Percentage      1815 non-null   float64
 6   12th_Percentage      1817 non-null   float64
 7   Attendance           1758 non-null   float64
 8   Backlogs             1820 non-null   int64
 9   Internship           1820 non-null   str
 10  Projects             1792 non-null   float64
 11  Certifications       1820 non-null   int64
 12  Programming_Skill    1790 non-null   float64
 13  Communication_Skill  1790 non-null   float64
 14  Aptitude_Score       1775 non-null   float64
 15  Placement_Status     1820 non-null   str
 16  Package_LPA          1789 non-null   str
 17  Graduation_Year      1820 non-null   int64
 18  Application_Date     1738 non-null   str
dtypes: float64(8), int64(3), str(8)
memory usage: 360.4 KB

In [9]:
df.describe()

,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Graduation_Year
count,1775.000000,1815.000000,1817.000000,1758.000000,1820.000000,1792.000000,1820.000000,1790.000000,1790.000000,1775.000000,1820.000000
mean,7.485887,74.585521,72.523627,79.988692,0.745604,2.684152,2.962637,5.413408,5.537989,65.473425,2024.494505
std,1.017833,10.010711,11.725665,10.366079,1.134499,1.465637,1.993869,2.839874,2.854680,14.782583,1.104975
min,0.000000,5.000000,10.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,2023.000000
25%,6.790000,68.300000,64.640000,73.375000,0.000000,2.000000,1.000000,3.000000,3.000000,55.505000,2024.000000
50%,7.500000,74.780000,72.550000,80.105000,0.000000,3.000000,3.000000,5.000000,5.000000,65.700000,2024.000000
75%,8.155000,81.420000,80.560000,86.965000,1.000000,4.000000,5.000000,8.000000,8.000000,75.755000,2025.000000
max,10.000000,100.000000,100.000000,100.000000,4.000000,15.000000,6.000000,15.000000,20.000000,100.000000,2026.000000

In [11]:
df.describe(include = 'object')

C:\Users\Darshan\AppData\Local\Temp\ipykernel_22256\1466716981.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = 'object')

,Student_ID,Name,Gender,Branch,Internship,Placement_Status,Package_LPA,Application_Date
count,1820,1820,1820,1820,1820,1820,1789,1738
unique,1800,1800,3,6,3,3,624,1302
top,ST1197,Student_1197,Male,CSE,No,Placed,0.0,2024-04-15
freq,2,2,905,536,979,1311,431,3

## Main Analytics

#### Placement Analytics

In [19]:
df['Placement_Status'].value_counts()

Placement_Status
Placed        1311
Not placed     493
Unknown         16
Name: count, dtype: int64

In [20]:
df['Placement_Status'].value_counts(normalize=True)*100

Placement_Status
Placed        72.032967
Not placed    27.087912
Unknown        0.879121
Name: proportion, dtype: float64

In [18]:
placement_rate = df['Placement_Status'].value_counts(normalize = True).mul(100).round(2)

#### Branch Analytics

In [22]:
branch_count = df['Branch'].value_counts()

In [23]:
branch_count

Branch
CSE           536
ECE           371
IT            352
Civil         268
Mechanical    266
Unknown        27
Name: count, dtype: int64

In [24]:
branch_placement = pd.crosstab(df['Branch'],df['Placement_Status'])

In [25]:
branch_placement

Placement_Status  Not placed  Placed  Unknown
Branch
CSE                      136     395        5
Civil                     75     190        3
ECE                       98     270        3
IT                        99     251        2
Mechanical                80     183        3
Unknown                    5      22        0

In [32]:
branch_placement_rate = df[df["Placement_Status"].isin(["Placed", "Not placed"])].groupby("Branch")['Placement_Status'].apply(lambda x: (x == "Placed").mean() * 100).round(2)

In [33]:
branch_placement_rate

Branch
CSE           74.39
Civil         71.70
ECE           73.37
IT            71.71
Mechanical    69.58
Unknown       81.48
Name: Placement_Status, dtype: float64

In [34]:
branch_summary = pd.DataFrame({"Total Students": df["Branch"].value_counts(),"Placement Rate (%)": branch_placement_rate})
branch_summary

            Total Students  Placement Rate (%)
Branch
CSE                    536               74.39
Civil                  268               71.70
ECE                    371               73.37
IT                     352               71.71
Mechanical             266               69.58
Unknown                 27               81.48

#### Academic Performance Analysis

In [37]:
academic_cols = ['CGPA','10th_Percentage','12th_Percentage','Attendance']
df[academic_cols].describe()

              CGPA  10th_Percentage  12th_Percentage   Attendance
count  1775.000000      1815.000000      1817.000000  1758.000000
mean      7.485887        74.585521        72.523627    79.988692
std       1.017833        10.010711        11.725665    10.366079
min       0.000000         5.000000        10.000000     5.000000
25%       6.790000        68.300000        64.640000    73.375000
50%       7.500000        74.780000        72.550000    80.105000
75%       8.155000        81.420000        80.560000    86.965000
max      10.000000       100.000000       100.000000   100.000000

In [40]:
df.groupby('Placement_Status')[academic_cols].mean().round(2)

                  CGPA  10th_Percentage  12th_Percentage  Attendance
Placement_Status
Not placed        7.37            74.52            72.88       79.76
Placed            7.53            74.56            72.37       80.05
Unknown           7.37            78.67            73.68       81.83

In [41]:
df.groupby('Placement_Status')[academic_cols].median().round(2)

                  CGPA  10th_Percentage  12th_Percentage  Attendance
Placement_Status
Not placed        7.32            74.78            73.10       79.62
Placed            7.55            74.74            72.35       80.21
Unknown           6.96            78.17            73.98       83.77

#### CGPA Analysis

In [42]:
df['CGPA'].describe()

count    1775.000000
mean        7.485887
std         1.017833
min         0.000000
25%         6.790000
50%         7.500000
75%         8.155000
max        10.000000
Name: CGPA, dtype: float64