### Placement Overview

The dataset contains 1820 students with known placement status.

- Placed: 1311 students (72.03 %)
- Not placed: 493 students (27.08 %)

This provides the baseline placement outcome for further analysis.

In [42]:
import pandas as pd
import numpy as np

df = pd.read_csv('Student_clean_data.csv')

## DATASET OVERVIEW

In [43]:
df.shape

(1820, 19)

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1820 entries, 0 to 1819
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           1820 non-null   str
 1   Name                 1820 non-null   str
 2   Gender               1820 non-null   str
 3   Branch               1820 non-null   str
 4   CGPA                 1775 non-null   float64
 5   10th_Percentage      1815 non-null   float64
 6   12th_Percentage      1817 non-null   float64
 7   Attendance           1758 non-null   float64
 8   Backlogs             1820 non-null   int64
 9   Internship           1820 non-null   str
 10  Projects             1792 non-null   float64
 11  Certifications       1820 non-null   int64
 12  Programming_Skill    1790 non-null   float64
 13  Communication_Skill  1790 non-null   float64
 14  Aptitude_Score       1775 non-null   float64
 15  Placement_Status     1820 non-null   str
 16  Package_LPA          1742 non-null   float64
 17  Graduation_Year      1820 non-null   int64
 18  Application_Date     1738 non-null   str
dtypes: float64(9), int64(3), str(7)
memory usage: 352.9 KB

In [45]:
df.describe()

,CGPA,10th_Percentage,12th_Percentage,Attendance,Backlogs,Projects,Certifications,Programming_Skill,Communication_Skill,Aptitude_Score,Package_LPA,Graduation_Year
count,1775.000000,1815.000000,1817.000000,1758.000000,1820.000000,1792.000000,1820.000000,1790.000000,1790.000000,1775.000000,1742.000000,1820.000000
mean,7.485887,74.585521,72.523627,79.988692,0.745604,2.684152,2.962637,5.413408,5.537989,65.473425,7.769122,2024.494505
std,1.017833,10.010711,11.725665,10.366079,1.134499,1.465637,1.993869,2.839874,2.854680,14.782583,5.176703,1.104975
min,0.000000,5.000000,10.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,0.000000,2023.000000
25%,6.790000,68.300000,64.640000,73.375000,0.000000,2.000000,1.000000,3.000000,3.000000,55.505000,1.500000,2024.000000
50%,7.500000,74.780000,72.550000,80.105000,0.000000,3.000000,3.000000,5.000000,5.000000,65.700000,9.425000,2024.000000
75%,8.155000,81.420000,80.560000,86.965000,1.000000,4.000000,5.000000,8.000000,8.000000,75.755000,11.040000,2025.000000
max,10.000000,100.000000,100.000000,100.000000,4.000000,15.000000,6.000000,15.000000,20.000000,100.000000,60.000000,2026.000000

In [46]:
df.describe(include = 'str')

,Student_ID,Name,Gender,Branch,Internship,Placement_Status,Application_Date
count,1820,1820,1820,1820,1820,1820,1738
unique,1800,1800,3,6,3,3,1302
top,ST1197,Student_1197,Male,CSE,No,Placed,2024-04-15
freq,2,2,905,536,979,1311,3

## Placement Status

In [47]:
df['Placement_Status'].value_counts()

Placement_Status
Placed        1311
Not placed     493
Unknown         16
Name: count, dtype: int64

In [48]:
df['Placement_Status'].value_counts(normalize = True)*100

Placement_Status
Placed        72.032967
Not placed    27.087912
Unknown        0.879121
Name: proportion, dtype: float64

#### Actual Placement Rate

In [49]:
known_placement = df[df["Placement_Status"].isin(["Placed", "Not placed"])]

In [50]:
placement_rate = ((known_placement['Placement_Status']=='Placed').mean()*100)

In [51]:
f"Placement Rate: {placement_rate:.2f}%"

'Placement Rate: 72.67%'

## Branch Status

In [52]:
df['Branch'].value_counts()

Branch
CSE           536
ECE           371
IT            352
Civil         268
Mechanical    266
Unknown        27
Name: count, dtype: int64

In [53]:
branch_wise_placement_count = pd.crosstab(df["Branch"],df["Placement_Status"])

In [54]:
branch_wise_placement_rate = (known_placement.groupby('Branch')['Placement_Status'].apply(lambda x:(x=='Placed').mean()*100).round(2))

In [55]:
branch_wise_placement_rate

Branch
CSE           74.39
Civil         71.70
ECE           73.37
IT            71.71
Mechanical    69.58
Unknown       81.48
Name: Placement_Status, dtype: float64

## Academic

In [56]:
academic_cols = ['CGPA','10th_Percentage','12th_Percentage','Attendance']

In [57]:
df[academic_cols].describe()

              CGPA  10th_Percentage  12th_Percentage   Attendance
count  1775.000000      1815.000000      1817.000000  1758.000000
mean      7.485887        74.585521        72.523627    79.988692
std       1.017833        10.010711        11.725665    10.366079
min       0.000000         5.000000        10.000000     5.000000
25%       6.790000        68.300000        64.640000    73.375000
50%       7.500000        74.780000        72.550000    80.105000
75%       8.155000        81.420000        80.560000    86.965000
max      10.000000       100.000000       100.000000   100.000000

In [58]:
academic_placement =df.groupby('Placement_Status')[academic_cols].mean().round(2)

In [59]:
academic_placement

                  CGPA  10th_Percentage  12th_Percentage  Attendance
Placement_Status
Not placed        7.37            74.52            72.88       79.76
Placed            7.53            74.56            72.37       80.05
Unknown           7.37            78.67            73.68       81.83

In [60]:
df.groupby('Placement_Status')[academic_cols].median().round(2)

                  CGPA  10th_Percentage  12th_Percentage  Attendance
Placement_Status
Not placed        7.32            74.78            73.10       79.62
Placed            7.55            74.74            72.35       80.21
Unknown           6.96            78.17            73.98       83.77

## Internship vs Placement

In [61]:
df['Internship'].value_counts()

Internship
No         979
Yes        813
Unknown     28
Name: count, dtype: int64

In [62]:
intern_place = pd.crosstab(df['Internship'],df['Placement_Status'])

In [63]:
intern_place

Placement_Status  Not placed  Placed  Unknown
Internship
No                       297     674        8
Unknown                   12      16        0
Yes                      184     621        8

In [64]:
intern_place_rate = pd.crosstab(df['Internship'],df['Placement_Status'],normalize = 'index').round(3)*100

In [65]:
intern_place_rate

Placement_Status  Not placed  Placed  Unknown
Internship
No                      30.3    68.8      0.8
Unknown                 42.9    57.1      0.0
Yes                     22.6    76.4      1.0

## Programming Skill

In [66]:
pro_skill = pd.crosstab(df["Placement_Status"],df["Programming_Skill"])

In [67]:
pro_skill

Programming_Skill,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,12.0,15.0
Placement_Status,,,,,,,,,,,,,
Not placed,1,61,66,55,54,49,44,47,48,31,28,2,0
Placed,1,114,115,119,139,138,127,152,130,117,133,2,1
Unknown,0,2,2,1,4,0,3,1,2,0,1,0,0

In [68]:
pro_skill_rate = pd.crosstab(df["Placement_Status"], df["Programming_Skill"],normalize="index").round(2) * 100

In [69]:
pro_skill_rate

Programming_Skill,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,12.0,15.0
Placement_Status,,,,,,,,,,,,,
Not placed,0.0,13.0,14.0,11.0,11.0,10.0,9.0,10.0,10.0,6.0,6.0,0.0,0.0
Placed,0.0,9.0,9.0,9.0,11.0,11.0,10.0,12.0,10.0,9.0,10.0,0.0,0.0
Unknown,0.0,12.0,12.0,6.0,25.0,0.0,19.0,6.0,12.0,0.0,6.0,0.0,0.0

## Communication Skill vs Placement

In [70]:
com_skill = pd.crosstab(df["Communication_Skill"], df["Placement_Status"])
com_skill

Placement_Status     Not placed  Placed  Unknown
Communication_Skill
0.0                           0       2        0
1.0                          53     101        0
2.0                          56     127        1
3.0                          51     117        0
4.0                          52     145        1
5.0                          58     132        1
6.0                          53     121        3
7.0                          40     147        1
8.0                          54     122        3
9.0                          39     143        2
10.0                         30     129        2
12.0                          0       2        0
20.0                          0       2        0

In [71]:
com_skill_rate = pd.crosstab(df["Placement_Status"],df['Communication_Skill'],normalize="index").round(2)*100
com_skill_rate

Communication_Skill,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,12.0,20.0
Placement_Status,,,,,,,,,,,,,
Not placed,0.0,11.0,12.0,10.0,11.0,12.0,11.0,8.0,11.0,8.0,6.0,0.0,0.0
Placed,0.0,8.0,10.0,9.0,11.0,10.0,9.0,11.0,9.0,11.0,10.0,0.0,0.0
Unknown,0.0,0.0,7.0,0.0,7.0,7.0,21.0,7.0,21.0,14.0,14.0,0.0,0.0

## Aptitude Score vs Placement

In [72]:
df.groupby('Placement_Status')['Aptitude_Score'].mean().round(2)

Placement_Status
Not placed    64.96
Placed        65.72
Unknown       60.75
Name: Aptitude_Score, dtype: float64

In [73]:
df.groupby('Placement_Status')['Aptitude_Score'].median().round(2)

Placement_Status
Not placed    65.84
Placed        65.63
Unknown       62.55
Name: Aptitude_Score, dtype: float64

## Packages Analysis

In [81]:
placed_students = df[df['Placement_Status'] == 'Placed']

In [82]:
placed_students['Package_LPA'].mean().round(2)

np.float64(10.35)

In [83]:
placed_students['Package_LPA'].median().round(2)

np.float64(10.27)

## Package by Branch

In [84]:
placed_students.groupby("Branch")["Package_LPA"].agg(["count", "mean", "median"]).round(2)

            count   mean  median
Branch
CSE           368  10.25   10.21
Civil         186  10.68   10.25
ECE           258  10.24   10.28
IT            247  10.39   10.44
Mechanical    180  10.31   10.05
Unknown        19  10.39    9.93